const GET_TASK_REQUEST = "GET_TASK_REQUEST";
const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
const GET_TASK_FAIL = "GET_TASK_FAIL";
const ADD_NEW_TASK = "ADD_NEW_TASK";

export { GET_TASK_REQUEST, GET_TASK_SUCCESS, GET_TASK_FAIL, ADD_NEW_TASK };
